    
- type: stBand
  id: STEvolversBand
  name: Evolvers
  maxMembers: 15
  managingRankId: 4
  hierarchy:
    1: Evolver
    2: EvolverPackFang
    3: EvolverSymbioteMedium
    4: EvolverSymbioteArchon
    5: EvolverPackAlpha
