- type: playTimeTracker
  id: JobStalker
- type: playTimeTracker
  id: JobMilitary
- type: playTimeTracker
  id: JobMilitaryStalker
- type: playTimeTracker
  id: JobBandit
- type: playTimeTracker
  id: JobPostulant
- type: playTimeTracker
  id: JobBishop
- type: playTimeTracker
  id: JobStalkerSci
- type: playTimeTracker
  id: JobSeraphims
- type: playTimeTracker
  id: JobStalkerAnomalist
- type: playTimeTracker
  id: StalkerAnomalistGuardian
- type: playTimeTracker
  id: JobJournalist
- type: playTimeTracker
  id: JobNeutral
- type: playTimeTracker
  id: JobPoisk

- type: playTimeTracker
  id: JobHeadMilitary
- type: playTimeTracker
  id: JobOfficerMilitary
- type: playTimeTracker
  id: JobHeadBandit
- type: playTimeTracker
  id: JobHeadStalkerSci
- type: playTimeTracker
  id: JobStalkerISSG
- type: playTimeTracker
  id: JobHeadSeraphims
- type: playTimeTracker
  id: JobMonolith
- type: playTimeTracker
  id: JobUN
- type: playTimeTracker
  id: JobDolg
- type: playTimeTracker
  id: JobHeadDolg
- type: playTimeTracker
  id: JobFreedom
- type: playTimeTracker
  id: JobHeadFreedom
- type: playTimeTracker
  id: JobSBU
- type: playTimeTracker
  id: JobRenegat
- type: playTimeTracker
  id: JobZavet
- type: playTimeTracker
  id: JobStalkerMercenary
- type: playTimeTracker
  id: JobStalkerHeadMercenary
- type: playTimeTracker
  id: JobGreh
- type: playTimeTracker
  id: JobDeserter
- type: playTimeTracker
  id: JobClearSky
- type: playTimeTracker
  id: JobJaba
- type: playTimeTracker
  id: JobMilitia
- type: playTimeTracker
  id: JobMilitiaCommander

- type: playTimeTracker
  id: JobDoctor
- type: playTimeTracker
  id: JobHeadDoctor

- type: playTimeTracker
  id: JobMayorCity
- type: playTimeTracker
  id: JobProkuror
- type: playTimeTracker
  id: JobMagistrate
- type: playTimeTracker
  id: JobPriest

- type: playTimeTracker
  id: JobStalkerBartender

# Эволверы и их группировки
- type: playTimeTracker
  id: JobEvolver

- type: playTimeTracker
  id: JobEvolverPackFang
- type: playTimeTracker
  id: JobEvolverPackAlpha

- type: playTimeTracker
  id: JobEvolverSymbioteMedium
- type: playTimeTracker
  id: JobEvolverSymbioteArchon
