- type: job
  id: StalkerZavet
  name: job-covenant
  icon: zavet
  description: job-covenant-desc
  playTimeTracker: JobZavet
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobZavet
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: StalkerZavetGear
  supervisors: Вы работаете на Высшие Силы.
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        groups:
          - Covenant
        tags:
          - Covenant
      - type: Bands
        band: Stalker
        bandIcon: zavet
        bandProto: STCovenantBand
        bandRankId: 2
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3

- type: startingGear
  id: StalkerZavetGear
  equipment:
    id: StalkerPDA
    belt: ClothingBeltStorageWaistbag
    torso: ClothingTorsoTurtlenecksCovenantHead
    legs: ClothingLegsJeansBlackCargo
    shoes: ClothingShoesBootsWork

- type: startingGear
  id: StalkerZavetLeaderGear
  equipment:
    id: StalkerPDA
    belt: ClothingBeltStorageWaistbag
    torso: ClothingTorsoTurtlenecksCovenant
    legs: ClothingLegsJeansBrownCargo
    shoes: ClothingShoesBootsWork
- type: stBand
  id: STCovenantBand
  name: Covenant
  factionId: Covenant
  maxMembers: 10
  managingRankId: 2
  hierarchy:
    1: StalkerZavet

