- type: job
  id: StalkerMercenary
  name: job-mercenary
  icon: merc
  description: job-mercenary-desc
  playTimeTracker: JobStalkerMercenary
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobStalkerMercenary
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: StalkerMercenaryGear
  supervisors: job-mercenary-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Merc
        - type: Bands
          altBand: stalker
          canChange: true
          band: Stalker
          bandIcon: merc
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: StalkerMercenaryGear
  equipment:
    id: BandPDA
    belt: ClothingBeltStorageWaistbag
    torso: STClothingTorsoJacketGray
    legs: STClothingLegsPantsGray
    shoes: ClothingShoesSwat


- type: job
  id: StalkerHeadMercenary
  name: job-head-mercenary
  icon: merc
  description: job-head-mercenary-desc
  playTimeTracker: JobStalkerHeadMercenary
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobStalkerHeadMercenary
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: StalkerHeadMercenaryGear
  supervisors: job-head-mercenary-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - HeadMerc
            - Merc
        - type: Bands
          altBand: stalker
          canChange: true
          band: Stalker
          bandIcon: merc
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: StalkerHeadMercenaryGear
  equipment:
    id: BandPDA
    belt: ClothingBeltStorageWaistbag
    neck: ClothingNeckDogtagBrigand
    eyes: ClothingEyesGlassesSunglasses
    torso: STClothingTorsoJacketGray
    legs: STClothingLegsPantsGray
    shoes: ClothingShoesSwat
