- type: job
  id: StalkerMonolith
  name: job-monolith
  icon: monolith
  description: job-monolith-desc
  playTimeTracker: JobMonolith
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobMonolith
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
  startingGear: MonolithGear
  supervisors: job-monolith-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        tags:
          - Monolith
      - type: Bands
        band: Stalker
        bandIcon: monolith
        bandProto: STMonolithBand
        bandRankId: 2
      - type: NpcFactionMember
        factions:
          - Mutated
      - type: Hunger
        baseDecayRate: 0
      - type: Thirst
        baseDecayRate: 0
      - type: PersonalDamageBlock
      - type: Damageable
        damageModifierSet: STPlayerMonolithModifierSet
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3
      - type: STAnomalyTipsViewing

- type: startingGear
  id: MonolithGear
  equipment:
    id: MonolithPDA
    torso: ClothingTorsoSweaterStalkerGreen
    legs: ClothingLegsJeansBlue
    shoes: ClothingShoesNovice
    back: ClothingBackpackDuffelBlackStalker
- type: stBand
  id: STMonolithBand
  name: Monolith
  factionId: Monolith
  maxMembers: 15
  managingRankId: 3
  hierarchy:
    1: StalkerMonolith

